-- ==========================================================
-- Ev Envanter & Garanti Takip - Supabase PostgreSQL Şeması
-- ==========================================================

-- 1. PROFILES TABLOSU (auth.users ile 1-1 İlişkili)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  email TEXT NOT NULL,
  avatar_url TEXT,
  expo_push_token TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. CATEGORIES TABLOSU
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  icon TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Varsayılan Kategorileri Ekle
INSERT INTO public.categories (id, name, icon) VALUES
  (1, 'Televizyon', 'tv'),
  (2, 'Bilgisayar', 'laptop'),
  (3, 'Telefon', 'smartphone'),
  (4, 'Tablet', 'tablet'),
  (5, 'Beyaz Eşya', 'refrigerator'),
  (6, 'Küçük Ev Aletleri', 'coffee'),
  (7, 'Mobilya', 'armchair'),
  (8, 'Mutfak Ürünleri', 'utensils'),
  (9, 'Oyun / Konsol', 'gamepad-2'),
  (10, 'Diğer', 'package')
ON CONFLICT (id) DO NOTHING;

-- 3. PRODUCTS TABLOSU
CREATE TABLE IF NOT EXISTS public.products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  brand TEXT,
  model TEXT,
  serial_number TEXT,
  purchase_date DATE,
  purchase_price NUMERIC(12, 2) DEFAULT 0 CHECK (purchase_price >= 0),
  warranty_duration_months INTEGER DEFAULT 24,
  warranty_end_date DATE NOT NULL,
  store_name TEXT,
  description TEXT,
  image_path TEXT,
  invoice_path TEXT,
  is_favorite BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- İndeksler (Sorgu ve Arama Performansı İçin)
CREATE INDEX IF NOT EXISTS idx_products_user_id ON public.products(user_id);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_warranty_end_date ON public.products(warranty_end_date);
CREATE INDEX IF NOT EXISTS idx_products_is_favorite ON public.products(is_favorite);
CREATE INDEX IF NOT EXISTS idx_products_search ON public.products USING gin(to_tsvector('turkish', coalesce(name, '') || ' ' || coalesce(brand, '') || ' ' || coalesce(model, '') || ' ' || coalesce(serial_number, '')));

-- 4. OTOMATİK PROFİL OLUŞTURMA TRIGGER'I
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', ''),
    new.email
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 5. ROW LEVEL SECURITY (RLS) POLİTİKALARI

-- Profiles RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Kullanıcı kendi profilini görebilir"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Kullanıcı kendi profilini ekleyebilir"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Kullanıcı kendi profilini güncelleyebilir"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- Categories RLS (Tüm giriş yapmış kullanıcılar görebilir)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Kategoriler herkes tarafından görüntülenebilir"
  ON public.categories FOR SELECT
  USING (true);

-- Products RLS (Kullanıcı yalnızca kendi ürünlerini yönetebilir)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Kullanıcı yalnızca kendi ürünlerini görebilir"
  ON public.products FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Kullanıcı yalnızca kendi adına ürün ekleyebilir"
  ON public.products FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Kullanıcı yalnızca kendi ürünlerini güncelleyebilir"
  ON public.products FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Kullanıcı yalnızca kendi ürünlerini silebilir"
  ON public.products FOR DELETE
  USING (auth.uid() = user_id);

-- 6. STORAGE BUCKET'LARI (Supabase Storage)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('invoices', 'invoices', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS Politikaları
CREATE POLICY "Görselleri herkes görüntüleyebilir"
  ON storage.objects FOR SELECT
  USING (bucket_id IN ('product-images', 'invoices'));

CREATE POLICY "Giriş yapmış kullanıcı görsel yükleyebilir"
  ON storage.objects FOR INSERT
  WITH CHECK (
    auth.role() = 'authenticated' AND
    bucket_id IN ('product-images', 'invoices')
  );

CREATE POLICY "Giriş yapmış kullanıcı kendi görselini güncelleyebilir/silebilir"
  ON storage.objects FOR DELETE
  USING (
    auth.role() = 'authenticated' AND
    bucket_id IN ('product-images', 'invoices')
  );
