import { StyleSheet } from 'react-native';
import { ThemeColors, SPACING, RADIUS, SHADOWS } from '../constants';

export const getStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.background,
      borderTopLeftRadius: RADIUS.xl,
      borderTopRightRadius: RADIUS.xl,
      paddingHorizontal: SPACING.lg,
      paddingTop: SPACING.md,
      paddingBottom: SPACING.xl,
      maxHeight: '90%',
    },
    handleBar: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.surfaceContainerHighest,
      alignSelf: 'center',
      marginBottom: SPACING.md,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: SPACING.md,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    headerIconBox: {
      width: 42,
      height: 42,
      borderRadius: RADIUS.md,
      backgroundColor: colors.tertiary + '18',
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.onBackground,
    },
    headerSubtitle: {
      fontSize: 12,
      color: colors.onSurfaceVariant,
      marginTop: 2,
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: RADIUS.full,
      backgroundColor: colors.surfaceContainerHigh,
      alignItems: 'center',
      justifyContent: 'center',
    },
    scrollArea: {
      maxHeight: 480,
    },
    scrollContent: {
      paddingBottom: SPACING.xl,
    },
    infoCallout: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.surfaceContainerLow,
      borderRadius: RADIUS.md,
      padding: SPACING.md,
      marginBottom: SPACING.lg,
    },
    infoCalloutText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
      color: colors.onSurfaceVariant,
    },
    fileSelectCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.surfaceContainerLowest,
      borderWidth: 1.5,
      borderColor: colors.tertiary + '40',
      borderStyle: 'dashed',
      borderRadius: RADIUS.lg,
      padding: SPACING.lg,
      marginBottom: SPACING.lg,
    },
    fileSelectLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    fileSelectIconCircle: {
      width: 44,
      height: 44,
      borderRadius: RADIUS.full,
      backgroundColor: colors.tertiary + '18',
      alignItems: 'center',
      justifyContent: 'center',
    },
    fileSelectTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.onBackground,
    },
    fileSelectSubtitle: {
      fontSize: 12,
      color: colors.onSurfaceVariant,
      marginTop: 2,
    },
    previewCard: {
      backgroundColor: colors.surfaceContainer,
      borderRadius: RADIUS.lg,
      padding: SPACING.md,
      marginBottom: SPACING.lg,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
    },
    previewHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    previewTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.onSurface,
    },
    previewBadge: {
      backgroundColor: colors.tertiaryContainer,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: RADIUS.full,
    },
    previewBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.onTertiaryContainer,
    },
    previewStatRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 4,
    },
    previewStatLabel: {
      fontSize: 13,
      color: colors.onSurfaceVariant,
    },
    previewStatValue: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.onBackground,
    },
    sampleList: {
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: colors.outlineVariant,
    },
    sampleTitle: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.onSurfaceVariant,
      marginBottom: 4,
    },
    sampleItem: {
      fontSize: 12,
      color: colors.onSurface,
      paddingVertical: 2,
    },
    manualSectionTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.onSurfaceVariant,
      marginBottom: 6,
    },
    jsonInput: {
      backgroundColor: colors.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
      borderRadius: RADIUS.md,
      padding: SPACING.md,
      fontSize: 12,
      fontFamily: 'monospace',
      color: colors.onBackground,
      height: 90,
      textAlignVertical: 'top',
      marginBottom: SPACING.lg,
    },
    actionButton: {
      backgroundColor: colors.tertiary,
      borderRadius: RADIUS.md,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: SPACING.sm,
    },
    actionButtonDisabled: {
      opacity: 0.5,
    },
    actionButtonText: {
      color: colors.onTertiary,
      fontSize: 15,
      fontWeight: '700',
    },
  });
