import { StyleSheet } from 'react-native';
import { ThemeColors, SPACING, RADIUS, SHADOWS } from '../constants';

export const getStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: SPACING.lg,
    },
    modalCard: {
      width: '100%',
      maxWidth: 380,
      backgroundColor: colors.surfaceContainerLowest,
      borderRadius: RADIUS.xl + 4,
      paddingHorizontal: SPACING.xl,
      paddingTop: SPACING.xl + 4,
      paddingBottom: SPACING.lg,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.outlineVariant + '40',
      ...SHADOWS.lg,
    },
    iconOuterCircle: {
      width: 76,
      height: 76,
      borderRadius: 38,
      backgroundColor: colors.primaryContainer,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: SPACING.md,
      borderWidth: 3,
      borderColor: colors.primary + '30',
      ...SHADOWS.sm,
    },
    title: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.onBackground,
      textAlign: 'center',
      letterSpacing: -0.3,
      marginBottom: 8,
    },
    description: {
      fontSize: 13.5,
      lineHeight: 20,
      color: colors.onSurfaceVariant,
      textAlign: 'center',
      marginBottom: SPACING.md,
      paddingHorizontal: 4,
    },
    featuresContainer: {
      width: '100%',
      backgroundColor: colors.surfaceContainerLow,
      borderRadius: RADIUS.lg,
      padding: SPACING.md,
      marginBottom: SPACING.md,
      gap: 10,
    },
    featureRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    featureIconBadge: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.primary + '18',
      alignItems: 'center',
      justifyContent: 'center',
    },
    featureText: {
      flex: 1,
      fontSize: 12.5,
      fontWeight: '600',
      color: colors.onSurface,
      lineHeight: 17,
    },
    privacyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      marginBottom: SPACING.lg,
      paddingHorizontal: 8,
    },
    privacyText: {
      fontSize: 11.5,
      color: colors.outline,
      fontWeight: '500',
    },
    actionsContainer: {
      width: '100%',
      gap: 10,
    },
    allowButton: {
      backgroundColor: colors.primary,
      borderRadius: RADIUS.full,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
      ...SHADOWS.sm,
    },
    allowButtonText: {
      color: colors.onPrimary,
      fontSize: 15,
      fontWeight: '700',
      letterSpacing: 0.2,
    },
    dismissButton: {
      paddingVertical: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dismissButtonText: {
      color: colors.onSurfaceVariant,
      fontSize: 13.5,
      fontWeight: '600',
    },
  });
